// Hand the runtime the patch binary and the patch's code sections.
//
// TWO THINGS A PATCH IS. Its CODE is recompiled to C and linked into this executable by name, so
// a patched function replaces the original the moment the link happens; that part needs nothing
// from here. Its DATA (the float constants clang keeps in a pool, an initialized static) lives in
// the patch ELF's own sections at the patch region of the emulated memory, and it only gets
// there because librecomp copies the patch binary in at start (`read_patch_data`), from what is
// registered here. Without this registration the patch code runs against memory that holds
// zeros where its constants should be, and every earlier phase of the post-parity plan ran that
// way by luck (their constants were immediates, their statics zero-initialized) until a sun drawn
// at the camera's eye gave it away. `.scaffold/post-parity/execution/issues.md`, PHASE-41.
//
// The section table also lets the runtime resolve a pointer INTO patch code, which is how a
// patched function set as a callback would be found. Nothing needs that yet.
//
// The binary is `patches/patches.bin`, written by the recompiler beside the generated C, and
// embedded by the same tool that embeds the interface shaders; the section table is generated by
// the recompiler beside it. Both are build output and neither is committed.

#include "game/game.h"

#include "patches_bin.h"

#include "librecomp/overlays.hpp"

// The patch's code sections and their functions, as the recompiler laid them out.
#include "../../RecompiledPatches/recomp_overlays.inl"

void oot::register_patches() {
    recomp::overlays::register_patches(reinterpret_cast<const char*>(oot_patches_bin), oot_patches_bin_size,
                                       section_table, sizeof(section_table) / sizeof(section_table[0]));
}
