// Register the recompiled code's sections with the runtime.
//
// An overlay is loaded at an address other than the one it was linked at, so its relocations have
// to be applied when the game loads it. The runtime does that, and this is where it is told what
// the sections ARE. A section missing from this table does not fail here: its relocations are
// simply never applied, and the result is a crash much later in code that looks correct.
//
// `recomp_overlays.inl` is generated by the recompiler from our config and is gitignored. It
// defines `section_table`, `num_sections` and `overlay_sections_by_index`.

#include "librecomp/overlays.hpp"
#include "librecomp/sections.h"

#include "game/game.h"

// Generated. 472 sections, of which 468 are the relocatable code overlays.
#include "../../RecompiledFuncs/recomp_overlays.inl"

void oot::register_overlays() {
    recomp::overlays::overlay_section_table_data_t sections{
        .code_sections = section_table,
        .num_code_sections = ARRLEN(section_table),
        .total_num_sections = num_sections,
    };

    recomp::overlays::overlays_by_index_t overlays{
        .table = overlay_sections_by_index,
        .len = ARRLEN(overlay_sections_by_index),
    };

    recomp::overlays::register_overlays(sections, overlays);
}

size_t oot::registered_section_count() {
    return num_sections;
}

size_t oot::registered_overlay_count() {
    return ARRLEN(overlay_sections_by_index);
}
