// GENERATED by tools/gen_warps.py. Do not edit; edit the tool's region map and run it.
//
// Every place a player can warp to in NTSC-U 1.0, nested by location: a region, the places
// in it, and where a place has more than one way in, its numbered entrances.
//
// The numbers are entrance indices, the same ones --warp takes on the command line and the
// same ones the game writes into nextEntranceIndex. Each is the FIRST row of its layer
// group, so the game still chooses the age and time of day layer itself.
//
// 15 regions, 102 places, 357 entrances,
// from 1556 rows of the decompilation's entrance table.

#pragma once

namespace oot::warps {

    struct Entrance {
        const char* label;   // "Entrance 4", or the place's own name where there is only one
        int index;           // what goes to set_pending_warp
    };

    struct Place {
        const char* name;
        const Entrance* entrances;
        int count;
    };

    struct Region {
        const char* name;
        const Place* places;
        int count;
    };

    // Kokiri Forest / Kokiri Forest (SCENE_KOKIRI_FOREST)
    inline constexpr Entrance ENTRANCES_0_0[] = {
        { "Entrance 0", 0x0EE },   // ENTR_KOKIRI_FOREST_0
        { "Entrance 1", 0x209 },   // ENTR_KOKIRI_FOREST_1
        { "Entrance 2", 0x20D },   // ENTR_KOKIRI_FOREST_2
        { "Entrance 3", 0x211 },   // ENTR_KOKIRI_FOREST_3
        { "Entrance 4", 0x266 },   // ENTR_KOKIRI_FOREST_4
        { "Entrance 5", 0x26A },   // ENTR_KOKIRI_FOREST_5
        { "Entrance 6", 0x286 },   // ENTR_KOKIRI_FOREST_6
        { "Entrance 7", 0x338 },   // ENTR_KOKIRI_FOREST_7
        { "Entrance 8", 0x33C },   // ENTR_KOKIRI_FOREST_8
        { "Entrance 9", 0x443 },   // ENTR_KOKIRI_FOREST_9
        { "Entrance 10", 0x447 },   // ENTR_KOKIRI_FOREST_10
        { "Entrance 11", 0x457 },   // ENTR_KOKIRI_FOREST_11
        { "Entrance 12", 0x5E8 },   // ENTR_KOKIRI_FOREST_12
    };

    // Kokiri Forest / Link's house (SCENE_LINKS_HOUSE)
    inline constexpr Entrance ENTRANCES_0_1[] = {
        { "Entrance 0", 0x0BB },   // ENTR_LINKS_HOUSE_0
        { "Entrance 1", 0x272 },   // ENTR_LINKS_HOUSE_1
    };

    // Kokiri Forest / Mido's house (SCENE_MIDOS_HOUSE)
    inline constexpr Entrance ENTRANCES_0_2[] = {
        { "Mido's house", 0x433 },   // ENTR_MIDOS_HOUSE_0
    };

    // Kokiri Forest / Saria's house (SCENE_SARIAS_HOUSE)
    inline constexpr Entrance ENTRANCES_0_3[] = {
        { "Saria's house", 0x437 },   // ENTR_SARIAS_HOUSE_0
    };

    // Kokiri Forest / Kokiri shop (SCENE_KOKIRI_SHOP)
    inline constexpr Entrance ENTRANCES_0_4[] = {
        { "Kokiri shop", 0x0C1 },   // ENTR_KOKIRI_SHOP_0
    };

    // Kokiri Forest / Know-It-All Brothers' house (SCENE_KNOW_IT_ALL_BROS_HOUSE)
    inline constexpr Entrance ENTRANCES_0_5[] = {
        { "Know-It-All Brothers' house", 0x0C9 },   // ENTR_KNOW_IT_ALL_BROS_HOUSE_0
    };

    // Kokiri Forest / The twins' house (SCENE_TWINS_HOUSE)
    inline constexpr Entrance ENTRANCES_0_6[] = {
        { "The twins' house", 0x09C },   // ENTR_TWINS_HOUSE_0
    };

    // Kokiri Forest / Inside the Deku Tree (SCENE_DEKU_TREE)
    inline constexpr Entrance ENTRANCES_0_7[] = {
        { "Entrance 0", 0x000 },   // ENTR_DEKU_TREE_0
        { "Entrance 1", 0x252 },   // ENTR_DEKU_TREE_1
    };

    // Kokiri Forest / Inside the Deku Tree: boss room (SCENE_DEKU_TREE_BOSS)
    inline constexpr Entrance ENTRANCES_0_8[] = {
        { "Inside the Deku Tree: boss room", 0x40F },   // ENTR_DEKU_TREE_BOSS_0
    };

    // Lost Woods / Lost Woods (SCENE_LOST_WOODS)
    inline constexpr Entrance ENTRANCES_1_0[] = {
        { "Entrance 0", 0x11E },   // ENTR_LOST_WOODS_0
        { "Entrance 1", 0x1A9 },   // ENTR_LOST_WOODS_1
        { "Entrance 2", 0x1AD },   // ENTR_LOST_WOODS_2
        { "Entrance 3", 0x1B1 },   // ENTR_LOST_WOODS_3
        { "Entrance 4", 0x4C6 },   // ENTR_LOST_WOODS_4
        { "Entrance 5", 0x4D2 },   // ENTR_LOST_WOODS_5
        { "Entrance 6", 0x4D6 },   // ENTR_LOST_WOODS_6
        { "Entrance 7", 0x4DA },   // ENTR_LOST_WOODS_7
        { "Entrance 8", 0x4DE },   // ENTR_LOST_WOODS_8
        { "Entrance 9", 0x5E0 },   // ENTR_LOST_WOODS_9
    };

    // Lost Woods / Sacred Forest Meadow (SCENE_SACRED_FOREST_MEADOW)
    inline constexpr Entrance ENTRANCES_1_1[] = {
        { "Entrance 0", 0x0FC },   // ENTR_SACRED_FOREST_MEADOW_0
        { "Entrance 1", 0x215 },   // ENTR_SACRED_FOREST_MEADOW_1
        { "Entrance 2", 0x600 },   // ENTR_SACRED_FOREST_MEADOW_2
        { "Entrance 3", 0x608 },   // ENTR_SACRED_FOREST_MEADOW_3
    };

    // Lost Woods / Forest Temple (SCENE_FOREST_TEMPLE)
    inline constexpr Entrance ENTRANCES_1_2[] = {
        { "Entrance 0", 0x169 },   // ENTR_FOREST_TEMPLE_0
        { "Entrance 1", 0x24E },   // ENTR_FOREST_TEMPLE_1
        { "Entrance 2", 0x584 },   // ENTR_FOREST_TEMPLE_2
    };

    // Lost Woods / Forest Temple: boss room (SCENE_FOREST_TEMPLE_BOSS)
    inline constexpr Entrance ENTRANCES_1_3[] = {
        { "Forest Temple: boss room", 0x00C },   // ENTR_FOREST_TEMPLE_BOSS_0
    };

    // Hyrule Field / Hyrule Field (SCENE_HYRULE_FIELD)
    inline constexpr Entrance ENTRANCES_2_0[] = {
        { "Entrance 0", 0x0CD },   // ENTR_HYRULE_FIELD_0
        { "Entrance 1", 0x17D },   // ENTR_HYRULE_FIELD_1
        { "Entrance 2", 0x181 },   // ENTR_HYRULE_FIELD_2
        { "Entrance 3", 0x185 },   // ENTR_HYRULE_FIELD_3
        { "Entrance 4", 0x189 },   // ENTR_HYRULE_FIELD_4
        { "Entrance 5", 0x18D },   // ENTR_HYRULE_FIELD_5
        { "Entrance 6", 0x1F9 },   // ENTR_HYRULE_FIELD_6
        { "Entrance 7", 0x1FD },   // ENTR_HYRULE_FIELD_7
        { "Entrance 8", 0x27A },   // ENTR_HYRULE_FIELD_8
        { "Entrance 9", 0x27E },   // ENTR_HYRULE_FIELD_9
        { "Entrance 10", 0x282 },   // ENTR_HYRULE_FIELD_10
        { "Entrance 11", 0x28A },   // ENTR_HYRULE_FIELD_11
        { "Entrance 12", 0x28E },   // ENTR_HYRULE_FIELD_12
        { "Entrance 13", 0x292 },   // ENTR_HYRULE_FIELD_13
        { "Entrance 14", 0x311 },   // ENTR_HYRULE_FIELD_14
        { "Entrance 15", 0x476 },   // ENTR_HYRULE_FIELD_15
        { "Entrance 16", 0x50F },   // ENTR_HYRULE_FIELD_16
        { "Entrance 17", 0x594 },   // ENTR_HYRULE_FIELD_17
    };

    // Lon Lon Ranch / Lon Lon Ranch (SCENE_LON_LON_RANCH)
    inline constexpr Entrance ENTRANCES_3_0[] = {
        { "Entrance 0", 0x157 },   // ENTR_LON_LON_RANCH_0
        { "Entrance 1", 0x2AE },   // ENTR_LON_LON_RANCH_1
        { "Entrance 2", 0x2E2 },   // ENTR_LON_LON_RANCH_2
        { "Entrance 3", 0x2E6 },   // ENTR_LON_LON_RANCH_3
        { "Entrance 4", 0x378 },   // ENTR_LON_LON_RANCH_4
        { "Entrance 5", 0x42F },   // ENTR_LON_LON_RANCH_5
        { "Entrance 6", 0x4CA },   // ENTR_LON_LON_RANCH_6
        { "Entrance 7", 0x4CE },   // ENTR_LON_LON_RANCH_7
        { "Entrance 8", 0x558 },   // ENTR_LON_LON_RANCH_8
        { "Entrance 9", 0x55C },   // ENTR_LON_LON_RANCH_9
        { "Entrance 10", 0x5D4 },   // ENTR_LON_LON_RANCH_10
    };

    // Lon Lon Ranch / The house and the tower (SCENE_LON_LON_BUILDINGS)
    inline constexpr Entrance ENTRANCES_3_1[] = {
        { "Entrance 0", 0x04F },   // ENTR_LON_LON_BUILDINGS_0
        { "Entrance 1", 0x5D0 },   // ENTR_LON_LON_BUILDINGS_1
        { "Entrance 2", 0x5E4 },   // ENTR_LON_LON_BUILDINGS_2
    };

    // Lon Lon Ranch / The stable (SCENE_STABLE)
    inline constexpr Entrance ENTRANCES_3_2[] = {
        { "The stable", 0x2F9 },   // ENTR_STABLE_0
    };

    // Market / Market entrance (SCENE_MARKET_ENTRANCE_DAY)
    inline constexpr Entrance ENTRANCES_4_0[] = {
        { "Entrance 0", 0x033 },   // ENTR_MARKET_ENTRANCE_DAY_0
        { "Entrance 1", 0x276 },   // ENTR_MARKET_ENTRANCE_DAY_1
        { "Entrance 2", 0x26E },   // ENTR_MARKET_ENTRANCE_DAY_2
    };

    // Market / Market (SCENE_MARKET_DAY)
    inline constexpr Entrance ENTRANCES_4_1[] = {
        { "Entrance 0", 0x0B1 },   // ENTR_MARKET_DAY_0
        { "Entrance 1", 0x25A },   // ENTR_MARKET_DAY_1
        { "Entrance 2", 0x25E },   // ENTR_MARKET_DAY_2
        { "Entrance 3", 0x262 },   // ENTR_MARKET_DAY_3
        { "Entrance 4", 0x29E },   // ENTR_MARKET_DAY_4
        { "Entrance 5", 0x2A2 },   // ENTR_MARKET_DAY_5
        { "Entrance 6", 0x3B8 },   // ENTR_MARKET_DAY_6
        { "Entrance 7", 0x3BC },   // ENTR_MARKET_DAY_7
        { "Entrance 8", 0x1CD },   // ENTR_MARKET_DAY_8
        { "Entrance 9", 0x1D1 },   // ENTR_MARKET_DAY_9
        { "Entrance 10", 0x1D5 },   // ENTR_MARKET_DAY_10
    };

    // Market / Back alley (SCENE_BACK_ALLEY_DAY)
    inline constexpr Entrance ENTRANCES_4_2[] = {
        { "Entrance 0", 0x0AD },   // ENTR_BACK_ALLEY_DAY_0
        { "Entrance 1", 0x29A },   // ENTR_BACK_ALLEY_DAY_1
        { "Entrance 2", 0x3C0 },   // ENTR_BACK_ALLEY_DAY_2
        { "Entrance 3", 0x067 },   // ENTR_BACK_ALLEY_DAY_3
        { "Entrance 4", 0x38C },   // ENTR_BACK_ALLEY_DAY_4
    };

    // Market / Back alley house (SCENE_BACK_ALLEY_HOUSE)
    inline constexpr Entrance ENTRANCES_4_3[] = {
        { "Back alley house", 0x43B },   // ENTR_BACK_ALLEY_HOUSE_0
    };

    // Market / Bazaar (SCENE_BAZAAR)
    inline constexpr Entrance ENTRANCES_4_4[] = {
        { "Entrance 0", 0x0B7 },   // ENTR_BAZAAR_0
        { "Entrance 1", 0x52C },   // ENTR_BAZAAR_1
    };

    // Market / Potion shop (SCENE_POTION_SHOP_MARKET)
    inline constexpr Entrance ENTRANCES_4_5[] = {
        { "Potion shop", 0x388 },   // ENTR_POTION_SHOP_MARKET_0
    };

    // Market / Bombchu shop (SCENE_BOMBCHU_SHOP)
    inline constexpr Entrance ENTRANCES_4_6[] = {
        { "Entrance 0", 0x390 },   // ENTR_BOMBCHU_SHOP_0
        { "Entrance 1", 0x528 },   // ENTR_BOMBCHU_SHOP_1
    };

    // Market / Bombchu bowling alley (SCENE_BOMBCHU_BOWLING_ALLEY)
    inline constexpr Entrance ENTRANCES_4_7[] = {
        { "Bombchu bowling alley", 0x507 },   // ENTR_BOMBCHU_BOWLING_ALLEY_0
    };

    // Market / Mask shop (SCENE_HAPPY_MASK_SHOP)
    inline constexpr Entrance ENTRANCES_4_8[] = {
        { "Mask shop", 0x530 },   // ENTR_HAPPY_MASK_SHOP_0
    };

    // Market / Treasure box shop (SCENE_TREASURE_BOX_SHOP)
    inline constexpr Entrance ENTRANCES_4_9[] = {
        { "Treasure box shop", 0x063 },   // ENTR_TREASURE_BOX_SHOP_0
    };

    // Market / Shooting gallery (SCENE_SHOOTING_GALLERY)
    inline constexpr Entrance ENTRANCES_4_10[] = {
        { "Entrance 0", 0x03B },   // ENTR_SHOOTING_GALLERY_0
        { "Entrance 0", 0x2EA },   // ENTR_TEST_SHOOTING_GALLERY_0
        { "Entrance 1", 0x16D },   // ENTR_SHOOTING_GALLERY_1
    };

    // Market / The dog lady's house (SCENE_DOG_LADY_HOUSE)
    inline constexpr Entrance ENTRANCES_4_11[] = {
        { "The dog lady's house", 0x398 },   // ENTR_DOG_LADY_HOUSE_0
    };

    // Market / Guard house (SCENE_MARKET_GUARD_HOUSE)
    inline constexpr Entrance ENTRANCES_4_12[] = {
        { "Guard house", 0x07E },   // ENTR_MARKET_GUARD_HOUSE_0
    };

    // Market / Temple of Time grounds (SCENE_TEMPLE_OF_TIME_EXTERIOR_DAY)
    inline constexpr Entrance ENTRANCES_4_13[] = {
        { "Entrance 0", 0x171 },   // ENTR_TEMPLE_OF_TIME_EXTERIOR_DAY_0
        { "Entrance 1", 0x472 },   // ENTR_TEMPLE_OF_TIME_EXTERIOR_DAY_1
    };

    // Market / Temple of Time (SCENE_TEMPLE_OF_TIME)
    inline constexpr Entrance ENTRANCES_4_14[] = {
        { "Entrance 0", 0x053 },   // ENTR_TEMPLE_OF_TIME_0
        { "Entrance 2", 0x2CA },   // ENTR_TEMPLE_OF_TIME_2
        { "Entrance 3", 0x320 },   // ENTR_TEMPLE_OF_TIME_3
        { "Entrance 4", 0x324 },   // ENTR_TEMPLE_OF_TIME_4
        { "Entrance 5", 0x58C },   // ENTR_TEMPLE_OF_TIME_5
        { "Entrance 6", 0x590 },   // ENTR_TEMPLE_OF_TIME_6
        { "Entrance 7", 0x5F4 },   // ENTR_TEMPLE_OF_TIME_7
    };

    // Hyrule Castle / Castle grounds (SCENE_HYRULE_CASTLE)
    inline constexpr Entrance ENTRANCES_5_0[] = {
        { "Entrance 0", 0x138 },   // ENTR_HYRULE_CASTLE_0
        { "Entrance 1", 0x23D },   // ENTR_HYRULE_CASTLE_1
        { "Entrance 2", 0x340 },   // ENTR_HYRULE_CASTLE_2
        { "Entrance 3", 0x4FA },   // ENTR_HYRULE_CASTLE_3
        { "Entrance 4", 0x47E },   // ENTR_HYRULE_CASTLE_4
    };

    // Hyrule Castle / Courtyard: the guards (SCENE_CASTLE_COURTYARD_GUARDS_DAY)
    inline constexpr Entrance ENTRANCES_5_1[] = {
        { "Entrance 0", 0x07A },   // ENTR_CASTLE_COURTYARD_GUARDS_DAY_0
        { "Entrance 1", 0x296 },   // ENTR_CASTLE_COURTYARD_GUARDS_DAY_1
    };

    // Hyrule Castle / Courtyard: the inner garden (SCENE_CASTLE_COURTYARD_ZELDA)
    inline constexpr Entrance ENTRANCES_5_2[] = {
        { "Entrance 0", 0x400 },   // ENTR_CASTLE_COURTYARD_ZELDA_0
        { "Entrance 1", 0x5F0 },   // ENTR_CASTLE_COURTYARD_ZELDA_1
    };

    // Kakariko Village / Kakariko Village (SCENE_KAKARIKO_VILLAGE)
    inline constexpr Entrance ENTRANCES_6_0[] = {
        { "Entrance 0", 0x0DB },   // ENTR_KAKARIKO_VILLAGE_0
        { "Entrance 1", 0x191 },   // ENTR_KAKARIKO_VILLAGE_1
        { "Entrance 2", 0x195 },   // ENTR_KAKARIKO_VILLAGE_2
        { "Entrance 3", 0x201 },   // ENTR_KAKARIKO_VILLAGE_3
        { "Entrance 4", 0x2A6 },   // ENTR_KAKARIKO_VILLAGE_4
        { "Entrance 5", 0x345 },   // ENTR_KAKARIKO_VILLAGE_5
        { "Entrance 6", 0x349 },   // ENTR_KAKARIKO_VILLAGE_6
        { "Entrance 7", 0x34D },   // ENTR_KAKARIKO_VILLAGE_7
        { "Entrance 8", 0x351 },   // ENTR_KAKARIKO_VILLAGE_8
        { "Entrance 9", 0x44B },   // ENTR_KAKARIKO_VILLAGE_9
        { "Entrance 10", 0x463 },   // ENTR_KAKARIKO_VILLAGE_10
        { "Entrance 11", 0x4EE },   // ENTR_KAKARIKO_VILLAGE_11
        { "Entrance 12", 0x4FF },   // ENTR_KAKARIKO_VILLAGE_12
        { "Entrance 13", 0x513 },   // ENTR_KAKARIKO_VILLAGE_13
        { "Entrance 14", 0x554 },   // ENTR_KAKARIKO_VILLAGE_14
        { "Entrance 15", 0x5DC },   // ENTR_KAKARIKO_VILLAGE_15
    };

    // Kakariko Village / Impa's house (SCENE_IMPAS_HOUSE)
    inline constexpr Entrance ENTRANCES_6_1[] = {
        { "Entrance 0", 0x39C },   // ENTR_IMPAS_HOUSE_0
        { "Entrance 1", 0x5C8 },   // ENTR_IMPAS_HOUSE_1
    };

    // Kakariko Village / The guest house (SCENE_KAKARIKO_CENTER_GUEST_HOUSE)
    inline constexpr Entrance ENTRANCES_6_2[] = {
        { "The guest house", 0x2FD },   // ENTR_KAKARIKO_CENTER_GUEST_HOUSE_0
    };

    // Kakariko Village / House of Skulltula (SCENE_HOUSE_OF_SKULLTULA)
    inline constexpr Entrance ENTRANCES_6_3[] = {
        { "House of Skulltula", 0x550 },   // ENTR_HOUSE_OF_SKULLTULA_0
    };

    // Kakariko Village / Potion shop (SCENE_POTION_SHOP_KAKARIKO)
    inline constexpr Entrance ENTRANCES_6_4[] = {
        { "Entrance 0", 0x384 },   // ENTR_POTION_SHOP_KAKARIKO_0
        { "Entrance 1", 0x3E8 },   // ENTR_POTION_SHOP_KAKARIKO_1
        { "Entrance 2", 0x3EC },   // ENTR_POTION_SHOP_KAKARIKO_2
    };

    // Kakariko Village / Potion shop back room (SCENE_POTION_SHOP_GRANNY)
    inline constexpr Entrance ENTRANCES_6_5[] = {
        { "Potion shop back room", 0x072 },   // ENTR_POTION_SHOP_GRANNY_0
    };

    // Kakariko Village / The windmill and the grave below it (SCENE_WINDMILL_AND_DAMPES_GRAVE)
    inline constexpr Entrance ENTRANCES_6_6[] = {
        { "Entrance 0", 0x44F },   // ENTR_WINDMILL_AND_DAMPES_GRAVE_0
        { "Entrance 1", 0x453 },   // ENTR_WINDMILL_AND_DAMPES_GRAVE_1
        { "Entrance 2", 0x503 },   // ENTR_WINDMILL_AND_DAMPES_GRAVE_2
    };

    // Kakariko Village / Graveyard (SCENE_GRAVEYARD)
    inline constexpr Entrance ENTRANCES_6_7[] = {
        { "Entrance 0", 0x0E4 },   // ENTR_GRAVEYARD_0
        { "Entrance 1", 0x205 },   // ENTR_GRAVEYARD_1
        { "Entrance 2", 0x355 },   // ENTR_GRAVEYARD_2
        { "Entrance 3", 0x359 },   // ENTR_GRAVEYARD_3
        { "Entrance 4", 0x35D },   // ENTR_GRAVEYARD_4
        { "Entrance 5", 0x361 },   // ENTR_GRAVEYARD_5
        { "Entrance 6", 0x50B },   // ENTR_GRAVEYARD_6
        { "Entrance 7", 0x568 },   // ENTR_GRAVEYARD_7
        { "Entrance 8", 0x580 },   // ENTR_GRAVEYARD_8
    };

    // Kakariko Village / Gravekeeper's hut (SCENE_GRAVEKEEPERS_HUT)
    inline constexpr Entrance ENTRANCES_6_8[] = {
        { "Gravekeeper's hut", 0x30D },   // ENTR_GRAVEKEEPERS_HUT_0
    };

    // Kakariko Village / Royal Family's tomb (SCENE_ROYAL_FAMILYS_TOMB)
    inline constexpr Entrance ENTRANCES_6_9[] = {
        { "Entrance 0", 0x02D },   // ENTR_ROYAL_FAMILYS_TOMB_0
        { "Entrance 1", 0x574 },   // ENTR_ROYAL_FAMILYS_TOMB_1
    };

    // Kakariko Village / The grave with the ReDeads (SCENE_REDEAD_GRAVE)
    inline constexpr Entrance ENTRANCES_6_10[] = {
        { "The grave with the ReDeads", 0x31C },   // ENTR_REDEAD_GRAVE_0
    };

    // Kakariko Village / The grave with the fairy's fountain (SCENE_GRAVE_WITH_FAIRYS_FOUNTAIN)
    inline constexpr Entrance ENTRANCES_6_11[] = {
        { "The grave with the fairy's fountain", 0x04B },   // ENTR_GRAVE_WITH_FAIRYS_FOUNTAIN_0
    };

    // Kakariko Village / Bottom of the Well (SCENE_BOTTOM_OF_THE_WELL)
    inline constexpr Entrance ENTRANCES_6_12[] = {
        { "Entrance 0", 0x098 },   // ENTR_BOTTOM_OF_THE_WELL_0
        { "Entrance 1", 0x5CC },   // ENTR_BOTTOM_OF_THE_WELL_1
    };

    // Kakariko Village / Shadow Temple (SCENE_SHADOW_TEMPLE)
    inline constexpr Entrance ENTRANCES_6_13[] = {
        { "Entrance 0", 0x037 },   // ENTR_SHADOW_TEMPLE_0
        { "Entrance 1", 0x2B2 },   // ENTR_SHADOW_TEMPLE_1
        { "Entrance 2", 0x2B6 },   // ENTR_SHADOW_TEMPLE_2
        { "Entrance 3", 0x4EA },   // ENTR_SHADOW_TEMPLE_3
    };

    // Kakariko Village / Shadow Temple: boss room (SCENE_SHADOW_TEMPLE_BOSS)
    inline constexpr Entrance ENTRANCES_6_14[] = {
        { "Shadow Temple: boss room", 0x413 },   // ENTR_SHADOW_TEMPLE_BOSS_0
    };

    // Death Mountain / Death Mountain Trail (SCENE_DEATH_MOUNTAIN_TRAIL)
    inline constexpr Entrance ENTRANCES_7_0[] = {
        { "Entrance 0", 0x13D },   // ENTR_DEATH_MOUNTAIN_TRAIL_0
        { "Entrance 1", 0x1B9 },   // ENTR_DEATH_MOUNTAIN_TRAIL_1
        { "Entrance 2", 0x1BD },   // ENTR_DEATH_MOUNTAIN_TRAIL_2
        { "Entrance 3", 0x242 },   // ENTR_DEATH_MOUNTAIN_TRAIL_3
        { "Entrance 4", 0x45B },   // ENTR_DEATH_MOUNTAIN_TRAIL_4
        { "Entrance 5", 0x47A },   // ENTR_DEATH_MOUNTAIN_TRAIL_5
    };

    // Death Mountain / Death Mountain Crater (SCENE_DEATH_MOUNTAIN_CRATER)
    inline constexpr Entrance ENTRANCES_7_1[] = {
        { "Entrance 0", 0x147 },   // ENTR_DEATH_MOUNTAIN_CRATER_0
        { "Entrance 1", 0x246 },   // ENTR_DEATH_MOUNTAIN_CRATER_1
        { "Entrance 2", 0x24A },   // ENTR_DEATH_MOUNTAIN_CRATER_2
        { "Entrance 3", 0x482 },   // ENTR_DEATH_MOUNTAIN_CRATER_3
        { "Entrance 4", 0x4F6 },   // ENTR_DEATH_MOUNTAIN_CRATER_4
        { "Entrance 5", 0x564 },   // ENTR_DEATH_MOUNTAIN_CRATER_5
    };

    // Death Mountain / Goron City (SCENE_GORON_CITY)
    inline constexpr Entrance ENTRANCES_7_2[] = {
        { "Entrance 0", 0x14D },   // ENTR_GORON_CITY_0
        { "Entrance 1", 0x1C1 },   // ENTR_GORON_CITY_1
        { "Entrance 2", 0x3FC },   // ENTR_GORON_CITY_2
        { "Entrance 3", 0x4E2 },   // ENTR_GORON_CITY_3
    };

    // Death Mountain / Goron shop (SCENE_GORON_SHOP)
    inline constexpr Entrance ENTRANCES_7_3[] = {
        { "Goron shop", 0x37C },   // ENTR_GORON_SHOP_0
    };

    // Death Mountain / Dodongo's Cavern (SCENE_DODONGOS_CAVERN)
    inline constexpr Entrance ENTRANCES_7_4[] = {
        { "Entrance 0", 0x004 },   // ENTR_DODONGOS_CAVERN_0
        { "Entrance 1", 0x0C5 },   // ENTR_DODONGOS_CAVERN_1
    };

    // Death Mountain / Dodongo's Cavern: boss room (SCENE_DODONGOS_CAVERN_BOSS)
    inline constexpr Entrance ENTRANCES_7_5[] = {
        { "Dodongo's Cavern: boss room", 0x40B },   // ENTR_DODONGOS_CAVERN_BOSS_0
    };

    // Death Mountain / Fire Temple (SCENE_FIRE_TEMPLE)
    inline constexpr Entrance ENTRANCES_7_6[] = {
        { "Entrance 0", 0x165 },   // ENTR_FIRE_TEMPLE_0
        { "Entrance 1", 0x175 },   // ENTR_FIRE_TEMPLE_1
    };

    // Death Mountain / Fire Temple: boss room (SCENE_FIRE_TEMPLE_BOSS)
    inline constexpr Entrance ENTRANCES_7_7[] = {
        { "Fire Temple: boss room", 0x305 },   // ENTR_FIRE_TEMPLE_BOSS_0
    };

    // Zora's River and Domain / Zora's River (SCENE_ZORAS_RIVER)
    inline constexpr Entrance ENTRANCES_8_0[] = {
        { "Entrance 0", 0x0EA },   // ENTR_ZORAS_RIVER_0
        { "Entrance 1", 0x199 },   // ENTR_ZORAS_RIVER_1
        { "Entrance 2", 0x19D },   // ENTR_ZORAS_RIVER_2
        { "Entrance 3", 0x1D9 },   // ENTR_ZORAS_RIVER_3
        { "Entrance 4", 0x1DD },   // ENTR_ZORAS_RIVER_4
    };

    // Zora's River and Domain / Zora's Domain (SCENE_ZORAS_DOMAIN)
    inline constexpr Entrance ENTRANCES_8_1[] = {
        { "Entrance 0", 0x108 },   // ENTR_ZORAS_DOMAIN_0
        { "Entrance 1", 0x1A1 },   // ENTR_ZORAS_DOMAIN_1
        { "Entrance 2", 0x3C4 },   // ENTR_ZORAS_DOMAIN_2
        { "Entrance 3", 0x153 },   // ENTR_ZORAS_DOMAIN_3
        { "Entrance 4", 0x328 },   // ENTR_ZORAS_DOMAIN_4
    };

    // Zora's River and Domain / Zora shop (SCENE_ZORA_SHOP)
    inline constexpr Entrance ENTRANCES_8_2[] = {
        { "Zora shop", 0x380 },   // ENTR_ZORA_SHOP_0
    };

    // Zora's River and Domain / Zora's Fountain (SCENE_ZORAS_FOUNTAIN)
    inline constexpr Entrance ENTRANCES_8_3[] = {
        { "Entrance 0", 0x10E },   // ENTR_ZORAS_FOUNTAIN_0
        { "Entrance 1", 0x221 },   // ENTR_ZORAS_FOUNTAIN_1
        { "Entrance 2", 0x225 },   // ENTR_ZORAS_FOUNTAIN_2
        { "Entrance 3", 0x3D4 },   // ENTR_ZORAS_FOUNTAIN_3
        { "Entrance 4", 0x3D8 },   // ENTR_ZORAS_FOUNTAIN_4
        { "Entrance 5", 0x394 },   // ENTR_ZORAS_FOUNTAIN_5
    };

    // Zora's River and Domain / Inside Jabu-Jabu (SCENE_JABU_JABU)
    inline constexpr Entrance ENTRANCES_8_4[] = {
        { "Entrance 0", 0x028 },   // ENTR_JABU_JABU_0
        { "Entrance 1", 0x407 },   // ENTR_JABU_JABU_1
    };

    // Zora's River and Domain / Inside Jabu-Jabu: boss room (SCENE_JABU_JABU_BOSS)
    inline constexpr Entrance ENTRANCES_8_5[] = {
        { "Inside Jabu-Jabu: boss room", 0x301 },   // ENTR_JABU_JABU_BOSS_0
    };

    // Zora's River and Domain / Ice Cavern (SCENE_ICE_CAVERN)
    inline constexpr Entrance ENTRANCES_8_6[] = {
        { "Entrance 0", 0x088 },   // ENTR_ICE_CAVERN_0
        { "Entrance 1", 0x5D8 },   // ENTR_ICE_CAVERN_1
    };

    // Lake Hylia / Lake Hylia (SCENE_LAKE_HYLIA)
    inline constexpr Entrance ENTRANCES_9_0[] = {
        { "Entrance 0", 0x102 },   // ENTR_LAKE_HYLIA_0
        { "Entrance 1", 0x219 },   // ENTR_LAKE_HYLIA_1
        { "Entrance 2", 0x21D },   // ENTR_LAKE_HYLIA_2
        { "Entrance 3", 0x3C8 },   // ENTR_LAKE_HYLIA_3
        { "Entrance 4", 0x3CC },   // ENTR_LAKE_HYLIA_4
        { "Entrance 5", 0x4E6 },   // ENTR_LAKE_HYLIA_5
        { "Entrance 6", 0x309 },   // ENTR_LAKE_HYLIA_6
        { "Entrance 7", 0x560 },   // ENTR_LAKE_HYLIA_7
        { "Entrance 8", 0x604 },   // ENTR_LAKE_HYLIA_8
        { "Entrance 9", 0x60C },   // ENTR_LAKE_HYLIA_9
    };

    // Lake Hylia / Lakeside laboratory (SCENE_LAKESIDE_LABORATORY)
    inline constexpr Entrance ENTRANCES_9_1[] = {
        { "Entrance 0", 0x043 },   // ENTR_LAKESIDE_LABORATORY_0
        { "Entrance 1", 0x1C5 },   // ENTR_LAKESIDE_LABORATORY_1
    };

    // Lake Hylia / Fishing pond (SCENE_FISHING_POND)
    inline constexpr Entrance ENTRANCES_9_2[] = {
        { "Fishing pond", 0x45F },   // ENTR_FISHING_POND_0
    };

    // Lake Hylia / Water Temple (SCENE_WATER_TEMPLE)
    inline constexpr Entrance ENTRANCES_9_3[] = {
        { "Entrance 0", 0x010 },   // ENTR_WATER_TEMPLE_0
        { "Entrance 1", 0x423 },   // ENTR_WATER_TEMPLE_1
    };

    // Lake Hylia / Water Temple: boss room (SCENE_WATER_TEMPLE_BOSS)
    inline constexpr Entrance ENTRANCES_9_4[] = {
        { "Water Temple: boss room", 0x417 },   // ENTR_WATER_TEMPLE_BOSS_0
    };

    // Gerudo Valley and the desert / Gerudo Valley (SCENE_GERUDO_VALLEY)
    inline constexpr Entrance ENTRANCES_10_0[] = {
        { "Entrance 0", 0x117 },   // ENTR_GERUDO_VALLEY_0
        { "Entrance 1", 0x1A5 },   // ENTR_GERUDO_VALLEY_1
        { "Entrance 2", 0x229 },   // ENTR_GERUDO_VALLEY_2
        { "Entrance 3", 0x22D },   // ENTR_GERUDO_VALLEY_3
        { "Entrance 4", 0x3D0 },   // ENTR_GERUDO_VALLEY_4
    };

    // Gerudo Valley and the desert / The carpenters' tent (SCENE_CARPENTERS_TENT)
    inline constexpr Entrance ENTRANCES_10_1[] = {
        { "The carpenters' tent", 0x3A0 },   // ENTR_CARPENTERS_TENT_0
    };

    // Gerudo Valley and the desert / Gerudo's Fortress (SCENE_GERUDOS_FORTRESS)
    inline constexpr Entrance ENTRANCES_10_2[] = {
        { "Entrance 0", 0x129 },   // ENTR_GERUDOS_FORTRESS_0
        { "Entrance 1", 0x231 },   // ENTR_GERUDOS_FORTRESS_1
        { "Entrance 2", 0x235 },   // ENTR_GERUDOS_FORTRESS_2
        { "Entrance 3", 0x239 },   // ENTR_GERUDOS_FORTRESS_3
        { "Entrance 4", 0x2AA },   // ENTR_GERUDOS_FORTRESS_4
        { "Entrance 5", 0x2BA },   // ENTR_GERUDOS_FORTRESS_5
        { "Entrance 6", 0x2BE },   // ENTR_GERUDOS_FORTRESS_6
        { "Entrance 7", 0x2C2 },   // ENTR_GERUDOS_FORTRESS_7
        { "Entrance 8", 0x2C6 },   // ENTR_GERUDOS_FORTRESS_8
        { "Entrance 9", 0x2D2 },   // ENTR_GERUDOS_FORTRESS_9
        { "Entrance 10", 0x2D6 },   // ENTR_GERUDOS_FORTRESS_10
        { "Entrance 11", 0x2DA },   // ENTR_GERUDOS_FORTRESS_11
        { "Entrance 12", 0x2DE },   // ENTR_GERUDOS_FORTRESS_12
        { "Entrance 13", 0x3A4 },   // ENTR_GERUDOS_FORTRESS_13
        { "Entrance 14", 0x3A8 },   // ENTR_GERUDOS_FORTRESS_14
        { "Entrance 15", 0x3AC },   // ENTR_GERUDOS_FORTRESS_15
        { "Entrance 16", 0x3B0 },   // ENTR_GERUDOS_FORTRESS_16
        { "Entrance 17", 0x3B4 },   // ENTR_GERUDOS_FORTRESS_17
        { "Entrance 18", 0x5F8 },   // ENTR_GERUDOS_FORTRESS_18
    };

    // Gerudo Valley and the desert / Thieves' Hideout (SCENE_THIEVES_HIDEOUT)
    inline constexpr Entrance ENTRANCES_10_3[] = {
        { "Entrance 0", 0x486 },   // ENTR_THIEVES_HIDEOUT_0
        { "Entrance 1", 0x48A },   // ENTR_THIEVES_HIDEOUT_1
        { "Entrance 2", 0x48E },   // ENTR_THIEVES_HIDEOUT_2
        { "Entrance 3", 0x492 },   // ENTR_THIEVES_HIDEOUT_3
        { "Entrance 4", 0x496 },   // ENTR_THIEVES_HIDEOUT_4
        { "Entrance 5", 0x49A },   // ENTR_THIEVES_HIDEOUT_5
        { "Entrance 6", 0x49E },   // ENTR_THIEVES_HIDEOUT_6
        { "Entrance 7", 0x4A2 },   // ENTR_THIEVES_HIDEOUT_7
        { "Entrance 8", 0x4A6 },   // ENTR_THIEVES_HIDEOUT_8
        { "Entrance 9", 0x4AA },   // ENTR_THIEVES_HIDEOUT_9
        { "Entrance 10", 0x4AE },   // ENTR_THIEVES_HIDEOUT_10
        { "Entrance 11", 0x4B2 },   // ENTR_THIEVES_HIDEOUT_11
        { "Entrance 12", 0x570 },   // ENTR_THIEVES_HIDEOUT_12
    };

    // Gerudo Valley and the desert / Gerudo Training Ground (SCENE_GERUDO_TRAINING_GROUND)
    inline constexpr Entrance ENTRANCES_10_4[] = {
        { "Gerudo Training Ground", 0x008 },   // ENTR_GERUDO_TRAINING_GROUND_0
    };

    // Gerudo Valley and the desert / Haunted Wasteland (SCENE_HAUNTED_WASTELAND)
    inline constexpr Entrance ENTRANCES_10_5[] = {
        { "Entrance 0", 0x130 },   // ENTR_HAUNTED_WASTELAND_0
        { "Entrance 1", 0x365 },   // ENTR_HAUNTED_WASTELAND_1
        { "Entrance 2", 0x369 },   // ENTR_HAUNTED_WASTELAND_2
    };

    // Gerudo Valley and the desert / Desert Colossus (SCENE_DESERT_COLOSSUS)
    inline constexpr Entrance ENTRANCES_10_6[] = {
        { "Entrance 0", 0x123 },   // ENTR_DESERT_COLOSSUS_0
        { "Entrance 1", 0x1E1 },   // ENTR_DESERT_COLOSSUS_1
        { "Entrance 2", 0x1E5 },   // ENTR_DESERT_COLOSSUS_2
        { "Entrance 3", 0x1E9 },   // ENTR_DESERT_COLOSSUS_3
        { "Entrance 4", 0x1ED },   // ENTR_DESERT_COLOSSUS_4
        { "Entrance 5", 0x1F1 },   // ENTR_DESERT_COLOSSUS_5
        { "Entrance 6", 0x1F5 },   // ENTR_DESERT_COLOSSUS_6
        { "Entrance 7", 0x57C },   // ENTR_DESERT_COLOSSUS_7
        { "Entrance 8", 0x610 },   // ENTR_DESERT_COLOSSUS_8
    };

    // Gerudo Valley and the desert / Spirit Temple (SCENE_SPIRIT_TEMPLE)
    inline constexpr Entrance ENTRANCES_10_7[] = {
        { "Entrance 0", 0x082 },   // ENTR_SPIRIT_TEMPLE_0
        { "Entrance 1", 0x2F5 },   // ENTR_SPIRIT_TEMPLE_1
        { "Entrance 2", 0x3F0 },   // ENTR_SPIRIT_TEMPLE_2
        { "Entrance 3", 0x3F4 },   // ENTR_SPIRIT_TEMPLE_3
        { "Entrance 4", 0x3F8 },   // ENTR_SPIRIT_TEMPLE_4
    };

    // Gerudo Valley and the desert / Spirit Temple: boss room (SCENE_SPIRIT_TEMPLE_BOSS)
    inline constexpr Entrance ENTRANCES_10_8[] = {
        { "Entrance 0", 0x08D },   // ENTR_SPIRIT_TEMPLE_BOSS_0
        { "Entrance 2", 0x5EC },   // ENTR_SPIRIT_TEMPLE_BOSS_2
    };

    // Ganon's Castle / Ganon's Tower (SCENE_GANONS_TOWER)
    inline constexpr Entrance ENTRANCES_11_0[] = {
        { "Entrance 0", 0x41B },   // ENTR_GANONS_TOWER_0
        { "Entrance 1", 0x427 },   // ENTR_GANONS_TOWER_1
        { "Entrance 2", 0x42B },   // ENTR_GANONS_TOWER_2
    };

    // Ganon's Castle / Inside the castle (SCENE_INSIDE_GANONS_CASTLE)
    inline constexpr Entrance ENTRANCES_11_1[] = {
        { "Entrance 0", 0x467 },   // ENTR_INSIDE_GANONS_CASTLE_0
        { "Entrance 1", 0x534 },   // ENTR_INSIDE_GANONS_CASTLE_1
        { "Entrance 2", 0x538 },   // ENTR_INSIDE_GANONS_CASTLE_2
        { "Entrance 3", 0x53C },   // ENTR_INSIDE_GANONS_CASTLE_3
        { "Entrance 4", 0x540 },   // ENTR_INSIDE_GANONS_CASTLE_4
        { "Entrance 5", 0x544 },   // ENTR_INSIDE_GANONS_CASTLE_5
        { "Entrance 6", 0x548 },   // ENTR_INSIDE_GANONS_CASTLE_6
        { "Entrance 7", 0x54C },   // ENTR_INSIDE_GANONS_CASTLE_7
    };

    // Ganon's Castle / Inside the castle, collapsing (SCENE_INSIDE_GANONS_CASTLE_COLLAPSE)
    inline constexpr Entrance ENTRANCES_11_2[] = {
        { "Inside the castle, collapsing", 0x56C },   // ENTR_INSIDE_GANONS_CASTLE_COLLAPSE_0
    };

    // Ganon's Castle / The tower collapsing: inside (SCENE_GANONS_TOWER_COLLAPSE_INTERIOR)
    inline constexpr Entrance ENTRANCES_11_3[] = {
        { "Entrance 0", 0x179 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_0
        { "Entrance 1", 0x134 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_1
        { "Entrance 2", 0x1B5 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_2
        { "Entrance 3", 0x256 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_3
        { "Entrance 4", 0x3DC },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_4
        { "Entrance 5", 0x3E0 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_5
        { "Entrance 6", 0x3E4 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_6
        { "Entrance 7", 0x4B6 },   // ENTR_GANONS_TOWER_COLLAPSE_INTERIOR_7
    };

    // Ganon's Castle / The tower collapsing: outside (SCENE_GANONS_TOWER_COLLAPSE_EXTERIOR)
    inline constexpr Entrance ENTRANCES_11_4[] = {
        { "Entrance 0", 0x43F },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_0
        { "Entrance 1", 0x4BA },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_1
        { "Entrance 2", 0x32C },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_2
        { "Entrance 3", 0x330 },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_3
        { "Entrance 4", 0x334 },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_4
        { "Entrance 5", 0x1C9 },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_5
        { "Entrance 6", 0x51C },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_6
        { "Entrance 7", 0x524 },   // ENTR_GANONS_TOWER_COLLAPSE_EXTERIOR_7
    };

    // Ganon's Castle / Ganondorf's chamber (SCENE_GANONDORF_BOSS)
    inline constexpr Entrance ENTRANCES_11_5[] = {
        { "Ganondorf's chamber", 0x41F },   // ENTR_GANONDORF_BOSS_0
    };

    // Ganon's Castle / The last fight (SCENE_GANON_BOSS)
    inline constexpr Entrance ENTRANCES_11_6[] = {
        { "The last fight", 0x517 },   // ENTR_GANON_BOSS_0
    };

    // Fountains and grottos / Grottos (SCENE_GROTTOS)
    inline constexpr Entrance ENTRANCES_12_0[] = {
        { "Entrance 0", 0x03F },   // ENTR_GROTTOS_0
        { "Entrance 1", 0x598 },   // ENTR_GROTTOS_1
        { "Entrance 2", 0x59C },   // ENTR_GROTTOS_2
        { "Entrance 3", 0x5A0 },   // ENTR_GROTTOS_3
        { "Entrance 4", 0x5A4 },   // ENTR_GROTTOS_4
        { "Entrance 5", 0x5A8 },   // ENTR_GROTTOS_5
        { "Entrance 6", 0x5AC },   // ENTR_GROTTOS_6
        { "Entrance 7", 0x5B0 },   // ENTR_GROTTOS_7
        { "Entrance 8", 0x5B4 },   // ENTR_GROTTOS_8
        { "Entrance 9", 0x5B8 },   // ENTR_GROTTOS_9
        { "Entrance 10", 0x5BC },   // ENTR_GROTTOS_10
        { "Entrance 11", 0x5C0 },   // ENTR_GROTTOS_11
        { "Entrance 12", 0x5C4 },   // ENTR_GROTTOS_12
        { "Entrance 13", 0x5FC },   // ENTR_GROTTOS_13
    };

    // Fountains and grottos / Fairy's fountain (SCENE_FAIRYS_FOUNTAIN)
    inline constexpr Entrance ENTRANCES_12_1[] = {
        { "Fairy's fountain", 0x36D },   // ENTR_FAIRYS_FOUNTAIN_0
    };

    // Fountains and grottos / Great Fairy's fountain: magic (SCENE_GREAT_FAIRYS_FOUNTAIN_MAGIC)
    inline constexpr Entrance ENTRANCES_12_2[] = {
        { "Entrance 0", 0x315 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_MAGIC_0
        { "Entrance 1", 0x4BE },   // ENTR_GREAT_FAIRYS_FOUNTAIN_MAGIC_1
        { "Entrance 2", 0x4C2 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_MAGIC_2
        { "Entrance 3", 0x4F2 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_MAGIC_3
    };

    // Fountains and grottos / Great Fairy's fountain: spells (SCENE_GREAT_FAIRYS_FOUNTAIN_SPELLS)
    inline constexpr Entrance ENTRANCES_12_3[] = {
        { "Entrance 0", 0x371 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_SPELLS_0
        { "Entrance 1", 0x578 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_SPELLS_1
        { "Entrance 2", 0x588 },   // ENTR_GREAT_FAIRYS_FOUNTAIN_SPELLS_2
    };

    // Sacred Realm and cutscenes / Chamber of the Sages (SCENE_CHAMBER_OF_THE_SAGES)
    inline constexpr Entrance ENTRANCES_13_0[] = {
        { "Entrance 0", 0x06B },   // ENTR_CHAMBER_OF_THE_SAGES_0
        { "Entrance 1", 0x2CE },   // ENTR_CHAMBER_OF_THE_SAGES_1
    };

    // Sacred Realm and cutscenes / Cutscene map (SCENE_CUTSCENE_MAP)
    inline constexpr Entrance ENTRANCES_13_1[] = {
        { "Cutscene map", 0x0A0 },   // ENTR_CUTSCENE_MAP_0
    };

    // Unused and test maps / Unused map 6E (SCENE_UNUSED_6E)
    inline constexpr Entrance ENTRANCES_14_0[] = {
        { "Unused map 6E", 0x014 },   // ENTR_UNUSED_6E
    };

    // Unused and test maps / Unused castle courtyard (SCENE_HAIRAL_NIWA2)
    inline constexpr Entrance ENTRANCES_14_1[] = {
        { "Unused castle courtyard", 0x076 },   // ENTR_HAIRAL_NIWA2_0
    };

    // Unused and test maps / Test map: sasatest (SCENE_SASATEST)
    inline constexpr Entrance ENTRANCES_14_2[] = {
        { "Test map: sasatest", 0x018 },   // ENTR_SASATEST_0
    };

    // Unused and test maps / Test map: syotes (SCENE_SYOTES)
    inline constexpr Entrance ENTRANCES_14_3[] = {
        { "Test map: syotes", 0x01C },   // ENTR_SYOTES_0
    };

    // Unused and test maps / Test map: syotes2 (SCENE_SYOTES2)
    inline constexpr Entrance ENTRANCES_14_4[] = {
        { "Test map: syotes2", 0x020 },   // ENTR_SYOTES2_0
    };

    // Unused and test maps / Test map: testroom (SCENE_TESTROOM)
    inline constexpr Entrance ENTRANCES_14_5[] = {
        { "Test map: testroom", 0x024 },   // ENTR_TESTROOM_0
    };

    // Unused and test maps / Test map: sutaru (SCENE_SUTARU)
    inline constexpr Entrance ENTRANCES_14_6[] = {
        { "Test map: sutaru", 0x047 },   // ENTR_SUTARU_0
    };

    // Unused and test maps / Test map: test01 (SCENE_TEST01)
    inline constexpr Entrance ENTRANCES_14_7[] = {
        { "Test map: test01", 0x094 },   // ENTR_TEST01_0
    };

    // Unused and test maps / Test map: depth test (SCENE_DEPTH_TEST)
    inline constexpr Entrance ENTRANCES_14_8[] = {
        { "Test map: depth test", 0x0B6 },   // ENTR_DEPTH_TEST_0
    };

    // Unused and test maps / Test map: besitu (SCENE_BESITU)
    inline constexpr Entrance ENTRANCES_14_9[] = {
        { "Test map: besitu", 0x520 },   // ENTR_BESITU_0
    };

    inline constexpr Place PLACES_0[] = {
        { "Kokiri Forest", ENTRANCES_0_0, 13 },
        { "Link's house", ENTRANCES_0_1, 2 },
        { "Mido's house", ENTRANCES_0_2, 1 },
        { "Saria's house", ENTRANCES_0_3, 1 },
        { "Kokiri shop", ENTRANCES_0_4, 1 },
        { "Know-It-All Brothers' house", ENTRANCES_0_5, 1 },
        { "The twins' house", ENTRANCES_0_6, 1 },
        { "Inside the Deku Tree", ENTRANCES_0_7, 2 },
        { "Inside the Deku Tree: boss room", ENTRANCES_0_8, 1 },
    };

    inline constexpr Place PLACES_1[] = {
        { "Lost Woods", ENTRANCES_1_0, 10 },
        { "Sacred Forest Meadow", ENTRANCES_1_1, 4 },
        { "Forest Temple", ENTRANCES_1_2, 3 },
        { "Forest Temple: boss room", ENTRANCES_1_3, 1 },
    };

    inline constexpr Place PLACES_2[] = {
        { "Hyrule Field", ENTRANCES_2_0, 18 },
    };

    inline constexpr Place PLACES_3[] = {
        { "Lon Lon Ranch", ENTRANCES_3_0, 11 },
        { "The house and the tower", ENTRANCES_3_1, 3 },
        { "The stable", ENTRANCES_3_2, 1 },
    };

    inline constexpr Place PLACES_4[] = {
        { "Market entrance", ENTRANCES_4_0, 3 },
        { "Market", ENTRANCES_4_1, 11 },
        { "Back alley", ENTRANCES_4_2, 5 },
        { "Back alley house", ENTRANCES_4_3, 1 },
        { "Bazaar", ENTRANCES_4_4, 2 },
        { "Potion shop", ENTRANCES_4_5, 1 },
        { "Bombchu shop", ENTRANCES_4_6, 2 },
        { "Bombchu bowling alley", ENTRANCES_4_7, 1 },
        { "Mask shop", ENTRANCES_4_8, 1 },
        { "Treasure box shop", ENTRANCES_4_9, 1 },
        { "Shooting gallery", ENTRANCES_4_10, 3 },
        { "The dog lady's house", ENTRANCES_4_11, 1 },
        { "Guard house", ENTRANCES_4_12, 1 },
        { "Temple of Time grounds", ENTRANCES_4_13, 2 },
        { "Temple of Time", ENTRANCES_4_14, 7 },
    };

    inline constexpr Place PLACES_5[] = {
        { "Castle grounds", ENTRANCES_5_0, 5 },
        { "Courtyard: the guards", ENTRANCES_5_1, 2 },
        { "Courtyard: the inner garden", ENTRANCES_5_2, 2 },
    };

    inline constexpr Place PLACES_6[] = {
        { "Kakariko Village", ENTRANCES_6_0, 16 },
        { "Impa's house", ENTRANCES_6_1, 2 },
        { "The guest house", ENTRANCES_6_2, 1 },
        { "House of Skulltula", ENTRANCES_6_3, 1 },
        { "Potion shop", ENTRANCES_6_4, 3 },
        { "Potion shop back room", ENTRANCES_6_5, 1 },
        { "The windmill and the grave below it", ENTRANCES_6_6, 3 },
        { "Graveyard", ENTRANCES_6_7, 9 },
        { "Gravekeeper's hut", ENTRANCES_6_8, 1 },
        { "Royal Family's tomb", ENTRANCES_6_9, 2 },
        { "The grave with the ReDeads", ENTRANCES_6_10, 1 },
        { "The grave with the fairy's fountain", ENTRANCES_6_11, 1 },
        { "Bottom of the Well", ENTRANCES_6_12, 2 },
        { "Shadow Temple", ENTRANCES_6_13, 4 },
        { "Shadow Temple: boss room", ENTRANCES_6_14, 1 },
    };

    inline constexpr Place PLACES_7[] = {
        { "Death Mountain Trail", ENTRANCES_7_0, 6 },
        { "Death Mountain Crater", ENTRANCES_7_1, 6 },
        { "Goron City", ENTRANCES_7_2, 4 },
        { "Goron shop", ENTRANCES_7_3, 1 },
        { "Dodongo's Cavern", ENTRANCES_7_4, 2 },
        { "Dodongo's Cavern: boss room", ENTRANCES_7_5, 1 },
        { "Fire Temple", ENTRANCES_7_6, 2 },
        { "Fire Temple: boss room", ENTRANCES_7_7, 1 },
    };

    inline constexpr Place PLACES_8[] = {
        { "Zora's River", ENTRANCES_8_0, 5 },
        { "Zora's Domain", ENTRANCES_8_1, 5 },
        { "Zora shop", ENTRANCES_8_2, 1 },
        { "Zora's Fountain", ENTRANCES_8_3, 6 },
        { "Inside Jabu-Jabu", ENTRANCES_8_4, 2 },
        { "Inside Jabu-Jabu: boss room", ENTRANCES_8_5, 1 },
        { "Ice Cavern", ENTRANCES_8_6, 2 },
    };

    inline constexpr Place PLACES_9[] = {
        { "Lake Hylia", ENTRANCES_9_0, 10 },
        { "Lakeside laboratory", ENTRANCES_9_1, 2 },
        { "Fishing pond", ENTRANCES_9_2, 1 },
        { "Water Temple", ENTRANCES_9_3, 2 },
        { "Water Temple: boss room", ENTRANCES_9_4, 1 },
    };

    inline constexpr Place PLACES_10[] = {
        { "Gerudo Valley", ENTRANCES_10_0, 5 },
        { "The carpenters' tent", ENTRANCES_10_1, 1 },
        { "Gerudo's Fortress", ENTRANCES_10_2, 19 },
        { "Thieves' Hideout", ENTRANCES_10_3, 13 },
        { "Gerudo Training Ground", ENTRANCES_10_4, 1 },
        { "Haunted Wasteland", ENTRANCES_10_5, 3 },
        { "Desert Colossus", ENTRANCES_10_6, 9 },
        { "Spirit Temple", ENTRANCES_10_7, 5 },
        { "Spirit Temple: boss room", ENTRANCES_10_8, 2 },
    };

    inline constexpr Place PLACES_11[] = {
        { "Ganon's Tower", ENTRANCES_11_0, 3 },
        { "Inside the castle", ENTRANCES_11_1, 8 },
        { "Inside the castle, collapsing", ENTRANCES_11_2, 1 },
        { "The tower collapsing: inside", ENTRANCES_11_3, 8 },
        { "The tower collapsing: outside", ENTRANCES_11_4, 8 },
        { "Ganondorf's chamber", ENTRANCES_11_5, 1 },
        { "The last fight", ENTRANCES_11_6, 1 },
    };

    inline constexpr Place PLACES_12[] = {
        { "Grottos", ENTRANCES_12_0, 14 },
        { "Fairy's fountain", ENTRANCES_12_1, 1 },
        { "Great Fairy's fountain: magic", ENTRANCES_12_2, 4 },
        { "Great Fairy's fountain: spells", ENTRANCES_12_3, 3 },
    };

    inline constexpr Place PLACES_13[] = {
        { "Chamber of the Sages", ENTRANCES_13_0, 2 },
        { "Cutscene map", ENTRANCES_13_1, 1 },
    };

    inline constexpr Place PLACES_14[] = {
        { "Unused map 6E", ENTRANCES_14_0, 1 },
        { "Unused castle courtyard", ENTRANCES_14_1, 1 },
        { "Test map: sasatest", ENTRANCES_14_2, 1 },
        { "Test map: syotes", ENTRANCES_14_3, 1 },
        { "Test map: syotes2", ENTRANCES_14_4, 1 },
        { "Test map: testroom", ENTRANCES_14_5, 1 },
        { "Test map: sutaru", ENTRANCES_14_6, 1 },
        { "Test map: test01", ENTRANCES_14_7, 1 },
        { "Test map: depth test", ENTRANCES_14_8, 1 },
        { "Test map: besitu", ENTRANCES_14_9, 1 },
    };

    inline constexpr Region REGIONS[] = {
        { "Kokiri Forest", PLACES_0, 9 },
        { "Lost Woods", PLACES_1, 4 },
        { "Hyrule Field", PLACES_2, 1 },
        { "Lon Lon Ranch", PLACES_3, 3 },
        { "Market", PLACES_4, 15 },
        { "Hyrule Castle", PLACES_5, 3 },
        { "Kakariko Village", PLACES_6, 15 },
        { "Death Mountain", PLACES_7, 8 },
        { "Zora's River and Domain", PLACES_8, 7 },
        { "Lake Hylia", PLACES_9, 5 },
        { "Gerudo Valley and the desert", PLACES_10, 9 },
        { "Ganon's Castle", PLACES_11, 7 },
        { "Fountains and grottos", PLACES_12, 4 },
        { "Sacred Realm and cutscenes", PLACES_13, 2 },
        { "Unused and test maps", PLACES_14, 10 },
    };

    inline constexpr int REGION_COUNT = 15;
    inline constexpr int PLACE_COUNT = 102;
    inline constexpr int ENTRANCE_COUNT = 357;

} // namespace oot::warps
