"""Blue noise masks for the renderer's sampling, by void and cluster (Ulichney 1993).

    python tools\blue_noise.py <output header>

Writes three 64 by 64 masks of 8 bit ranks as a C++ header, one per color channel of the
renderer's noise atlas. The renderer (rt64-patches, rt64_raytracing_bluenoise.cpp) turns them into
the 64 slices the shaders index by frame, each slice the mask shifted by a golden ratio step, so
one mask gives a sequence that is blue in space on every frame and decorrelated between frames.

Pure Python on purpose: the machine has no numpy, and this runs once, offline, into a committed
table. Seeded, so the table is reproducible byte for byte. About a minute per mask.

Phase 54 of .scaffold/upgrades/phases.md replaced the interleaved gradient placeholder with this.
"""
import math
import random
import sys

SIZE = 64
COUNT = SIZE * SIZE
SIGMA = 1.9
CHANNELS = 3
SEED = 0x0EE


def kernel_table() -> list[float]:
    """The toroidal Gaussian, as a table indexed by (dy * SIZE + dx) for the wrapped offsets."""
    table = [0.0] * COUNT
    for dy in range(SIZE):
        wy = min(dy, SIZE - dy)
        for dx in range(SIZE):
            wx = min(dx, SIZE - dx)
            table[dy * SIZE + dx] = math.exp(-(wx * wx + wy * wy) / (2.0 * SIGMA * SIGMA))
    return table


KERNEL = kernel_table()


def add_energy(energy: list[float], index: int, sign: float) -> None:
    py, px = divmod(index, SIZE)
    for y in range(SIZE):
        row = ((y - py) % SIZE) * SIZE
        base = y * SIZE
        for x in range(SIZE):
            energy[base + x] += sign * KERNEL[row + ((x - px) % SIZE)]


def tightest_cluster(energy: list[float], pattern: list[bool]) -> int:
    best, best_value = -1, -1.0
    for i in range(COUNT):
        if pattern[i] and energy[i] > best_value:
            best, best_value = i, energy[i]
    return best


def largest_void(energy: list[float], pattern: list[bool]) -> int:
    best, best_value = -1, float("inf")
    for i in range(COUNT):
        if not pattern[i] and energy[i] < best_value:
            best, best_value = i, energy[i]
    return best


def mask(seed: int) -> list[int]:
    rng = random.Random(seed)

    # The initial binary pattern: about a tenth of the pixels on, then relaxed until the tightest
    # cluster and the largest void are the same pixel.
    ones = COUNT // 10
    pattern = [False] * COUNT
    for i in rng.sample(range(COUNT), ones):
        pattern[i] = True
    energy = [0.0] * COUNT
    for i in range(COUNT):
        if pattern[i]:
            add_energy(energy, i, 1.0)
    while True:
        cluster = tightest_cluster(energy, pattern)
        pattern[cluster] = False
        add_energy(energy, cluster, -1.0)
        void = largest_void(energy, pattern)
        if void == cluster:
            pattern[cluster] = True
            add_energy(energy, cluster, 1.0)
            break
        pattern[void] = True
        add_energy(energy, void, 1.0)

    rank = [0] * COUNT

    # Phase one: remove the ones, tightest cluster first, ranking downward.
    work = pattern[:]
    work_energy = energy[:]
    remaining = ones
    while remaining > 0:
        cluster = tightest_cluster(work_energy, work)
        work[cluster] = False
        add_energy(work_energy, cluster, -1.0)
        remaining -= 1
        rank[cluster] = remaining

    # Phase two: fill the voids of the initial pattern, largest first, ranking upward, until half
    # the pixels are on.
    work = pattern[:]
    work_energy = energy[:]
    count = ones
    while count < COUNT // 2:
        void = largest_void(work_energy, work)
        work[void] = True
        add_energy(work_energy, void, 1.0)
        rank[void] = count
        count += 1

    # Phase three: the rest, in the energy of the zeros: the tightest cluster of zeros is the
    # largest void of the ones, so the pattern inverts and the search continues.
    inverse = [not v for v in work]
    inverse_energy = [0.0] * COUNT
    for i in range(COUNT):
        if inverse[i]:
            add_energy(inverse_energy, i, 1.0)
    while count < COUNT:
        cluster = tightest_cluster(inverse_energy, inverse)
        inverse[cluster] = False
        add_energy(inverse_energy, cluster, -1.0)
        rank[cluster] = count
        count += 1

    return [r * 256 // COUNT for r in rank]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    out = sys.argv[1]
    masks = []
    for channel in range(CHANNELS):
        print(f"mask {channel + 1} of {CHANNELS}", flush=True)
        masks.append(mask(SEED + channel))

    lines = [
        "//",
        "// RT64, the renderer's patch series (OoT: Recompiled), patch 0005.",
        "//",
        "// GENERATED by tools/blue_noise.py, which is where to look for the reasoning; do not edit.",
        f"// Three {SIZE} by {SIZE} blue noise masks of 8 bit ranks, void and cluster with sigma {SIGMA},",
        f"// seeds {SEED:#x} to {SEED + CHANNELS - 1:#x}, one per color channel of the noise atlas.",
        "//",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace RT64 {",
        f"    static const uint32_t BlueNoiseMaskSize = {SIZE};",
        f"    static const uint32_t BlueNoiseMaskChannels = {CHANNELS};",
        f"    static const uint8_t BlueNoiseMasks[{CHANNELS}][{COUNT}] = {{",
    ]
    for m in masks:
        lines.append("        {")
        for row in range(SIZE):
            values = ", ".join(f"{v:3d}" for v in m[row * SIZE:(row + 1) * SIZE])
            lines.append(f"            {values},")
        lines.append("        },")
    lines += ["    };", "};", ""]
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("WRITTEN", out, len(lines), "lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
