"""Turn a compiled shader blob into a C header holding a byte array.

Build time only, never shipped. RT64 has its own helper for this, but its CMake functions resolve
paths against RT64's own PROJECT_SOURCE_DIR, so they cannot compile a shader that lives in our
tree. This does the same job for ours without reaching into a vendored library's internals.

    python tools/embed_binary.py <input.dxil> <symbol_name> <output.h>
"""

import io
import os
import sys


def main(argv):
    if len(argv) != 4:
        print(__doc__)
        return 2

    src, symbol, dst = argv[1], argv[2], argv[3]
    data = io.open(src, "rb").read()
    if not data:
        print("embed_binary: %s is empty, which means the shader compile produced nothing" % src)
        return 1

    out = []
    out.append("// Generated by tools/embed_binary.py from %s. Do not edit." % os.path.basename(src))
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstddef>")
    out.append("#include <cstdint>")
    out.append("")
    out.append("static const uint8_t %s[] = {" % symbol)
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02X" % b for b in data[i:i + 16])
        out.append("    " + row + ",")
    out.append("};")
    out.append("")
    out.append("static const size_t %s_size = sizeof(%s);" % (symbol, symbol))
    out.append("")

    text = "\n".join(out)

    # Only rewrite when the content actually changed, so a rebuild does not cascade through every
    # translation unit that includes it.
    if os.path.exists(dst):
        try:
            if io.open(dst, encoding="utf-8").read() == text:
                return 0
        except OSError:
            pass

    directory = os.path.dirname(dst)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    io.open(dst, "w", encoding="utf-8", newline="\n").write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
